# Generated by Django 3.0.7 on 2020-06-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0002_auto_20200606_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='perfil/avatar.png', upload_to='perfil/'),
        ),
    ]
